parameters:
- name: serviceConnectionName
  type: string

jobs:

- job: Build
  displayName: 'Build'

  pool:
    vmImage: 'ubuntu-latest'

  steps:

  - task: AzureCLI@2
    displayName: "Build Bicep files"
    inputs:
      connectedServiceNameARM: ${{ parameters.serviceConnectionName }}
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        az bicep build --file main.bicep

  - task: PublishPipelineArtifact@1
    displayName: 'Upload deployment files'
    condition: "and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))"
    inputs:
      targetPath: deploy
      artifactName: 'deploy'
      artifactType: 'pipeline'
      parallel: true