parameters:
- name: environmentName
  type: string
- name: subscription
  type: string
- name: devopsEnvironment
  type: string
  default: 'XXX Development'
  values:
  - 'XXX Development'
  - 'XXX Test'
  - 'XXX Production'

jobs:
  - deployment: '<deployment_name>'
    displayName: 'Deploy'

    pool:
      vmImage: 'ubuntu-latest'

    environment: '${{ parameters.devopsEnvironment }}'
    strategy:
      runOnce:
        deploy:

          steps:
            - download: current
              displayName: Download Deployment Files
              artifact: deploy

            - task: AzureCLI@2
              displayName: 'Provision Azure resources'
              inputs:
                workingDirectory: '$(Pipeline.Workspace)/deploy'
                azureSubscription: ${{ parameters.subscription }}
                scriptType: pscore
                scriptLocation: inlineScript
                inlineScript: |
                    az deployment sub create --location westeurope --template-file main.bicep --parameters main.parameters-${{ parameters.environmentName }}.json
